### ISSUE TITLE
Some problem while executing code

### ISSUE THREAD

**Issue by tao840813** [FreyrS/dMaSIF#17]
Hi , i tried to executed some command codes from benchmark_scripts. 

However, I met some problems:
1. There are some dimension problem when the program loading PyG dataset
    collate  TypeError: __cat_dim__() takes 3 positional arguments but 4 were given
    So i modified the code in data.py from
    def __cat_dim__(self, key, value):
    to 
    def __cat_dim__(self, key, value, *args, **kwargs):

2.  atoms_to_points_normals
    Here comes some error like
    File exists: '/home/user/.cache/pykeops-1.5-cpython-38//build-pybind11_template-libKeOps_template_40f62f56de'  
      

   /home/user/.cache/pykeops-1.5-cpython-38:
         formula: Sum_Reduction(Exp(Minus(Sqrt(Sum(Square((Var(0,3,0) - Var(1,3,1))))))),1)
         aliases: Var(0,3,0); Var(1,3,1); 
         dtype  : float32
  ... 
    make: *** 「KeOps_formula」。 。
          
          --------------------- MAKE DEBUG -----------------
          Command '['cmake', '--build', '.', '--target', 'KeOps_formula', '--', 'VERBOSE=1']' returned non-zero exit status 2.

**Comment by zshyang** [comment]
Hi @tao840813 

I am also trying to run their repo. I met the same problem as you have mentioned. 

For problem 1, I think you have solved that problem. The following sentences are just for a supplementary purpose. 

The reason we have this problem is because of the version issue of `torch_geometric`.  You could see the difference between version [1.6.1](https://pytorch-geometric.readthedocs.io/en/1.6.1/modules/data.html) and [latest](https://pytorch-geometric.readthedocs.io/en/latest/modules/data.html) version. Their `__cat_dim__` function have different input requirements. 

For problem 2, I did not meet the exact error. But I think it is the similar problem that relates to the version of `KeOps`. I have some errors when I use `pip install pykeops` but using `pip install pykeops=1.4.1` solves the problem.

Best regards!

**Comment by tao840813** [comment]
Hi @zshyang 

For problem 2, it turns out that I installed wrong gcc version so that pykeops didn't install properly.
These problems are already solved right now.



Thank you for your response!
