### ISSUE TITLE
Runtime and memory much higher than described

### ISSUE THREAD

**Issue by rmwu** [FreyrS/dMaSIF#24]
Hello! I'm trying to run the search model on ~40k protein pairs, and on a single A6000, it takes approximately 50s per pair, and even with a batch size of 1, I often run out of memory (47.5 G total capacity).

Is there any preprocessing you would recommend to speed this up or reduce the memory cost?

**Comment by rmwu** [comment]
An update– I've tried running the proteins through individually, once per encoder, then running the loss computation on these "precomputed" embeddings + coordinates (symmetrizing with 1+2 and 2+1 where applicable). Would this be a valid way of using the search model?

**Comment by rmwu** [comment]
I see, the reported benchmarks were per-patch, so it's not surprising that whole protein - whole protein is slow.

**Comment by linminhtoo** [comment]
do you face the issue that the GPU VRAM usage creeps up slowly (memory leakage) and after several epochs, the CUDA memory runs out? this is quite inconvenient as I only have 8GB VRAM. I can get around it by resuming from the last checkpoint, but it would be much better if I could fix it. I'm not sure if it's due to `pykeops` or `torch_geometric`

**Comment by rmwu** [comment]
I'm not sure... It did run a couple of batches (of inference) before overflowing memory but for me, the main bottleneck was the P1, P2 cross computations. I could run inference on individual proteins just fine using their trained model, and haven't tried finetuning yet. I also currently only have one tmux pane that can run ```pykeops``` haha...

**Comment by jeanfeydy** [comment]
Hi @rmwu,

Thanks for your interest in our work :-)
Would you mind telling us a little bit more about your performance issues?
I am especially curious about your run times vs. protein sizes, and the meaning of your last remark about the tmux pane.
Please note that currently, dMaSIF is not well optimized for large proteins (with more than N=10k atoms): the implementation does not “truncate” interactions between points that are e.g. 50A away from each other, which means that you pay a O(N^2) computational time that becomes cumbersome when N exceeds ~10k. Fixing this could be done in the future, but this wasn’t a big priority for us - and I don’t what are @FreyrS ’s plans for the future, since his PhD is coming to an end pretty soon.

Best regards,
Jean
