### ISSUE TITLE
how can I run the PDL1 example by dmasif?

### ISSUE THREAD

**Issue by jiyanbio** [FreyrS/dMaSIF#5]
There're not clear instructions for downstream analysis by dmasif, such as docking.

**Comment by FreyrS** [comment]
We haven't thoroughly tested the downstream tasks for dmasif. In principle you could use a similar docking protocol as the one used in masif but replace the descriptors and interface predictions with the ones from dmasif. You will also have to change the patch extraction method in masif since you won't have a mesh to work with anymore, you could do this by approximating the geodesic distances like done in dmasif. The parameters of the docking protocol have to be fine-tuned for dmasif.
We'll try to benchmark these downstream tasks soon.
